function reconstruct(SS)
    %if loading SS object externally, this method initializes the
    %afpars property (which was not initialized in previous
    %versions of SS). more properties can be added to this method
    SS.afpars = struct('trange', [SS.time(1) SS.time(end)], ...
                    'rez', 1, ...
                    'spktype', 'clean', ...
                    'resprange', .025, ...
                    'channelrels', zeros(0, 3));
end